version: 2.1

commands:
  deploy-dev:
    description: "Command to deploy hugo to dev"
    steps:
      - run: hugo deploy --target trishafernandes-dev
  deploy-prod:
    description: "Command to deploy hugo to prod"
    steps:
      - run: hugo deploy --target trishafernandes-prod

executors:
  docker-image:
    docker:
      - image: trisha0996/alpine-hugo:0.1

jobs:
  test:
    executor: docker-image
    steps:
      - run: echo 'CircleCI config test'
  get-code:
    executor: docker-image
    steps:
      - checkout
      - run: echo 'Code received!'
  staging:
    executor: docker-image
    steps:
      - deploy-dev
  production:
    executor: docker-image
    steps:
      - deploy-prod

workflows:
  version: 2
  publish:
    jobs:
      - test
      - get-code:
          requires:
            - test
      - staging:
          requires:
            - get-code
      - hold:
          type: approval
          requires:
            - get-code
          filters:
            branches:
              ignore: master
      - production:
          requires:
            - hold
          filters:
            branches:
              ignore: master