version: 2.1

commands:
  deploy-dev:
    description: "Command to deploy hugo to dev"
    steps:
      - run: hugo deploy --target trishafernandes-dev
  deploy-prod:
    description: "Command to deploy hugo to prod"
    steps:
      - run: hugo deploy --target trishafernandes-prod
  gcloud-auth:
    steps:
      - run:
          name: Authenticate to Google
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > /tmp/gcloud-service-key.json

executors:
  docker-image:
    docker:
      - image: trisha0996/alpine-hugo:0.4

jobs:
  staging:
    executor: docker-image
    steps:
      - checkout
      - gcloud-auth
      - deploy-dev
  production:
    executor: docker-image
    steps:
      - checkout
      - gcloud-auth
      - deploy-prod

workflows:
  version: 2
  publish:
    jobs:
      - staging
      - hold:
          type: approval
          requires:
            - staging
          filters:
            branches:
              ignore: master
      - production:
          requires:
            - hold
          filters:
            branches:
              ignore: master